name: Check Packer Format and Syntax

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, synchronize, closed]

env:
  PRODUCT_VERSION: '1.10.1'

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: 'packer init ./packer'

      - name: Run `packer format`
        id: format
        run: 'packer fmt -check ./packer'

      - name: Run `packer validate`
        id: validate
        run: cd packer && packer validate .
