name: Run Packer Build

on:
  pull_request:
    branches: ['main']
  # pull_request:
  #   types: [closed]

env:
  PRODUCT_VERSION: '1.10.1'

jobs:
  packer-build:
    runs-on: ubuntu-latest
    # if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: 'packer init ./packer'

      - name: Build Artifact
        run: cd packer && packer build -var-file=variables.dev.json .
        # env:
        #   GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
